name: NodeJS with Vite

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      working-directory: ./frontend
      run: |
        echo "Current working directory before npm install:"
        pwd
        echo "Listing files in current directory:"
        ls -F
        echo "Checking for package.json:"
        test -f package.json && echo "package.json found in $(pwd)" || echo "package.json NOT found in $(pwd)"
        npm install

    - name: Build with Vite
      working-directory: ./frontend
      run: |
        echo "Current working directory before vite build:"
        pwd
        echo "Listing files in current directory:"
        ls -F
        npm run build
